version: '3.7'

services: 
  main:
    container_name: main
    build:
      context: .
      target: development
      dockerfile: ./infra/node-14/dockerfile
    volumes: 
      - ./app:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file: 
      - .env
    networks: 
      - backend

networks: 
  backend:
    driver: bridge