FROM node:14-alpine As development

WORKDIR /usr/src/app

COPY app/package*.json ./

RUN npm install --only=development

COPY app/ .



FROM node:14-alpine As production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY app/package*.json ./

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]